tools:
  jdk: 8
  maven: 3.5.0

triggers:
  - manual: Build
  - manual:
      name: Build RC
      call: rc  
flows:
  default:
    try:
      # build the product & deploy to remote nexus (after merge)
      - exposeVars(maven)
      - mvn -U clean deploy
  pr:
    # build the code for submitted PR 
    - mvn clean install
  rc:
    # create a release candidate
    # original cmd
    - mvn -B release:clean release:prepare release:perform -Dnexus.staging.maven.plugin.version=1.6.4 -Darguments="-Dmaven.javadoc.skip=true"    
      
