# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
# More info here as well
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

name: Gozer-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checking out code...
      uses: actions/checkout@v2
      
    - name: setting up JDK...
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: compiling...
      run: mvn compile
      
    - name: running unit tests...
      run: mvn test
            
    - name: buiding jar file...
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
    - name: Upload Code Coverage Report
      if: success()
      run: |
        curl -s https://codecov.io/bash | bash
        
# TODO: deploy SNAP-SHOT 
